# Your Application #
title: Styleguide
version: 1.0

# Frodo Config #
permalink: ":title.html"
pygments: true
exclude: [templates, README.md, .gitignore, .gitkeep, .sass-cache]
frodo_url: http://code.fbrandel.de/frodo
frodo_version: 0.1.0